version: '3.6'
services:
  bookshelf-app:
    container_name: bookshelf-app
    build:
      context: .
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/srv:cached
    working_dir: /srv
    depends_on:
      - bookshelf-db

  adminer:
    image: adminer:4.7.8
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - bookshelf-db

  bookshelf-db:
    image: postgres:13.1
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  dbvol:
